packages:
  - devops-codelib
  - devops-environment
  - devops-atomstore
  - devops-ticket
  - devops-pipeline
  - devops-quality
  - devops-nav
  - devops-turbo
  - devops-stream
  - devops-metrics
  - devops-manage
  - devops-permission
  - bk-pipeline
  - bk-permission
