name: Agent CI

on:
  push:
    branches: [master]
    paths:
    - 'src/agent/**'
  pull_request:
    branches: [master, release-*]
    paths:
    - 'src/agent/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build agent
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.6
    - run: make clean all
      working-directory: src/agent/
    - uses: actions/upload-artifact@v1
      with:
        name: agent
        path: src/agent/bin/
