name: Agent CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'src/agent/agent/**'
  pull_request:
    branches: [ master, release-* ]
    paths: 
      - 'src/agent/agent/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.6
      - uses: actions/checkout@v2
      - run: make clean all
        working-directory: src/agent/agent/
      - uses: actions/upload-artifact@v1
        with:
          name: agent
          path: src/agent/agent/bin/
