# 每天定时生成缓存
name: Daily Cache
on:
  schedule:
  - cron: '* * * * *' # 每天 UTC 时间 17:00 (东八区1点) 执行 TODO
jobs:
  backend:
    name: Build backend
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master
    - name: init mysql
      run: |
        export MYSQL_PWD=root
        for i in *.sql;do echo $i;mysql -h 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot < $i;done
      working-directory: support-files/sql
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "8"
        cache: "gradle"
    - name: Gradle Build Backend Service
      working-directory: src/backend/ci
      run: |
        ./gradlew clean -x test build :core:worker:worker-agent:shadowJar \
        -DmysqlURL=127.0.0.1:${{ job.services.mysql.ports['3306'] }} -DmysqlUser=root -DmysqlPasswd=root --no-daemon
    - name: Gradle Build Backend Service -- CLOUD NATIVE
      working-directory: src/backend/ci
      run: |
        ./gradlew clean test build -x test :core:worker:worker-agent:shadowJar -Ddevops.assemblyMode=KUBERNETES \
        -DmysqlURL=127.0.0.1:${{ job.services.mysql.ports['3306'] }} -DmysqlUser=root -DmysqlPasswd=root --no-daemon
    - name: Gradle Build Turbo Service
      working-directory: src/backend/turbo
      run: |
        ./gradlew clean copyToRelease
