# 每天定时生成缓存
name: Daily Cache
on:
  schedule:
  - cron: '0 17 * * *' # 每天 UTC 时间 17:00 (东八区1点) 执行
  workflow_dispatch:

jobs:
  backend:
    name: Build backend
    uses: ./.github/workflows/backend.yml
