# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [master]
    paths:
      - "src/frontend/**"
  pull_request:
    branches: [master, release-*]
    paths:
      - "src/frontend/**"
  workflow_dispatch:
  workflow_call:
    inputs:
      upload:
        required: true
        type: string

jobs:
  frontend:
    name: Build frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: prefer offline
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm --prefer-offline && pnpm install
        working-directory: src/frontend
      - run: |
          pnpm -v
          export NODE_OPTIONS=--openssl-legacy-provider
          pnpm public
        working-directory: src/frontend
      - uses: actions/upload-artifact@v3
        if: ${{ inputs.upload == 'true'  }}
        with:
          name: frontend
          path: src/frontend/frontend/
