# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [master]
    paths:
      - "src/frontend/**"
  pull_request:
    branches: [master, release-*]
    paths:
      - "src/frontend/**"
  workflow_dispatch:

jobs:
  frontend:
    name: Build frontend
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install project dependencies
      run: yarn --prefer-offline
    - run: yarn install && yarn start && yarn public
      working-directory: src/frontend
    - uses: actions/upload-artifact@v1
      with:
        name: frontend
        path: src/frontend/frontend/
