name: Tag Release
on:
  push:
    tags:
    - "v*"

jobs:
  frontend:
    name: Build frontend
    with:
      upload: true
    uses: ./.github/workflows/frontend.yml

  agent:
    name: Build agent
    with:
      upload: true
    uses: ./.github/workflows/agent.yml

  backend:
    name: Build backend
    with:
      upload: true
    uses: ./.github/workflows/backend.yml

  releaseAll:
    name: Release All
    runs-on: ubuntu-20.04
    needs: [frontend, agent, backend]
    steps:
    - name: download bkci-slim
      uses: actions/download-artifact@v3
      with:
        name: bkci-slim
        path: ./
    - name: download bkci-chart
      uses: actions/download-artifact@v3
      with:
        name: bkci-chart
        path: ./
    - name: get change log file
      id: get_version_file
      run: |
        version=${{ github.ref_name }}
        version=$(echo ${version:1})
        version=`echo $version | sed 's/-/./g'`
        major=`echo $version | cut -d. -f1`
        minor=`echo $version | cut -d. -f2`
        echo "version_file=CHANGELOG/CHANGELOG-$major.$minor.md"
        echo "version_file=CHANGELOG/CHANGELOG-$major.$minor.md" >> $GITHUB_OUTPUT
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: "bk-ci ${{ github.ref_name }}"
        draft: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "See <a href='https://github.com/TencentBlueKing/bk-ci/blob/master/${{steps.get_version_file.outputs.version_file}}'>the CHANGELOG</a> for more details."
        artifacts: "bkci-slim.tar.gz,bk-ci-charts.tgz"
